# Generated by Django 5.1 on 2024-09-07 07:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupen_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Coupen',
            new_name='Coupon',
        ),
        migrations.RenameModel(
            old_name='UserCoupen',
            new_name='UserCoupon',
        ),
    ]
