# Generated by Django 5.1 on 2024-09-07 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupen_app', '0002_rename_coupen_coupon_rename_usercoupen_usercoupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
