# Generated by Django 5.1 on 2024-09-06 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0004_wishlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
