# Generated by Django 5.1 on 2024-09-24 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransation',
            name='transaction_type',
            field=models.CharField(choices=[('refund', 'Refund'), ('cancellation', 'Cancellation'), ('debited', 'Debited')], max_length=20),
        ),
    ]
