# Generated by Django 5.1 on 2024-09-12 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0005_alter_orderitem_status_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='return_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('Order Pending', 'Order Pending'), ('Order confirmed', 'Order confirmed'), ('Shipped', 'Shipped'), ('Out For Delivery', 'Out For Delivery'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('Approve Returned', 'Approve Returned'), ('Reject Returned', 'Reject Returned')], default='Order Pending', max_length=20),
        ),
    ]
