# Generated by Django 5.1 on 2024-09-12 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0006_orderitem_return_reason_alter_orderitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('Order Pending', 'Order Pending'), ('Order confirmed', 'Order confirmed'), ('Shipped', 'Shipped'), ('Out For Delivery', 'Out For Delivery'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('Requested Return', 'Requested Return'), ('Approve Returned', 'Approve Returned'), ('Reject Returned', 'Reject Returned')], default='Order Pending', max_length=20),
        ),
    ]
