# Generated by Django 5.1 on 2024-09-21 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0007_alter_orderitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Success', 'Success'), ('Failure', 'Failure')], default='Pending', max_length=10),
        ),
    ]
