# Generated by Django 5.1 on 2024-08-24 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category_app', '0002_category_category_image_category_category_offer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_unit',
            field=models.CharField(blank=True, choices=[('kg', 'Kilogram'), ('g', 'Gram'), ('packet', 'Packet')], max_length=50, null=True),
        ),
    ]
