# Generated by Django 5.1 on 2024-08-20 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuth', '0002_remove_otp_expires_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTP',
        ),
    ]
