# Generated by Django 5.1 on 2024-08-20 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminAuth', '0002_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
